const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const gitHash = execSync('git rev-parse --short HEAD').toString().trim();
const buildDate = new Date().toISOString();

const versionInfo = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const versionInfo = {
  gitHash: '${gitHash}',
  buildDate: '${buildDate}'
};
`;

const outputPath = path.join(__dirname, '../src/environments/version.ts');
fs.writeFileSync(outputPath, versionInfo);

console.log(`Version info generated: ${gitHash} at ${buildDate}`);
